CREATE VIEW Invoice.vwRegisterDetail
AS
WITH register AS (
    SELECT
        StartOn,
        InvoiceNumber,
        ProjectCode,
        ObjectCode,
        CashCode,
        CashDescription,
        TaxCode,
        TaxDescription,
        SubjectCode,
        ParentSubjectCode,
        InvoiceTypeCode,
        InvoiceStatusCode,
        InvoicedOn,
        DueOn,
        ExpectedOn,
        CAST(Quantity AS float) AS Quantity,
        CAST(InvoiceValue AS float) AS InvoiceValue,
        CAST(TaxValue AS float) AS TaxValue,
        PaymentTerms,
        Printed,
        SubjectName,
        UserName,
        UserId,
        InvoiceStatus,
        CashPolarityCode,
        InvoiceType,
        CAST(1 AS bit) AS IsProject,
        ObjectDescription AS ItemReference
    FROM Invoice.vwRegisterProjects

    UNION ALL

    SELECT
        StartOn,
        InvoiceNumber,
        ProjectCode,
        NULL AS ObjectCode,
        CashCode,
        CashDescription,
        TaxCode,
        TaxDescription,
        SubjectCode,
        ParentSubjectCode,
        InvoiceTypeCode,
        InvoiceStatusCode,
        InvoicedOn,
        DueOn,
        ExpectedOn,
        CAST(0 AS float) AS Quantity,
        CAST(InvoiceValue AS float) AS InvoiceValue,
        CAST(TaxValue AS float) AS TaxValue,
        PaymentTerms,
        Printed,
        SubjectName,
        UserName,
        UserId,
        InvoiceStatus,
        CashPolarityCode,
        InvoiceType,
        CAST(0 AS bit) AS IsProject,
        ItemReference
    FROM Invoice.vwRegisterItems
)
SELECT
    StartOn,
    InvoiceNumber,
    ProjectCode,
    ObjectCode,
    CashCode,
    CashDescription,
    TaxCode,
    TaxDescription,
    SubjectCode,
    ParentSubjectCode,
    InvoiceTypeCode,
    InvoiceStatusCode,
    InvoicedOn,
    DueOn,
    ExpectedOn,
    PaymentTerms,
    Printed,
    SubjectName,
    UserName,
    UserId,
    InvoiceStatus,
    CashPolarityCode,
    InvoiceType,
    Quantity,
    InvoiceValue,
    TaxValue,
    InvoiceValue + TaxValue AS TotalValue,
    IsProject,
    ItemReference
FROM register;
