//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeControl.Node.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlServerName {
            get {
                return ((string)(this["SqlServerName"]));
            }
            set {
                this["SqlServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlUserName {
            get {
                return ((string)(this["SqlUserName"]));
            }
            set {
                this["SqlUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DatabaseName {
            get {
                return ((string)(this["DatabaseName"]));
            }
            set {
                this["DatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AuthenticationMode {
            get {
                return ((int)(this["AuthenticationMode"]));
            }
            set {
                this["AuthenticationMode"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=IAM;Initial Catalog=tcNode;Integrated Security=True")]
        public string tcNodeConnectionString {
            get {
                return ((string)(this["tcNodeConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>tc_upgrade_3_23_2</string>\r\n  <string>tc_upgrade_3_24_1</string>\r\n  <strin" +
            "g>tc_upgrade_3_24_2</string>\r\n  <string>tc_upgrade_3_24_3</string>\r\n  <string>tc" +
            "_upgrade_3_24_4</string>\r\n  <string>tc_upgrade_3_24_5</string>\r\n  <string>tc_upg" +
            "rade_3_24_6</string>\r\n  <string>tc_upgrade_3_25_1</string>\r\n  <string>tc_upgrade" +
            "_3_26_1</string>\r\n  <string>tc_upgrade_3_27_1</string>\r\n  <string>tc_upgrade_3_2" +
            "8_1</string>\r\n  <string>tc_upgrade_3_28_2</string>\r\n  <string>tc_upgrade_3_28_3<" +
            "/string>\r\n  <string>tc_upgrade_3_28_4</string>\r\n  <string>tc_upgrade_3_28_5</str" +
            "ing>\r\n  <string>tc_upgrade_3_29_1</string>\r\n  <string>tc_upgrade_3_29_2</string>" +
            "\r\n  <string>tc_upgrade_3_29_3</string>\r\n  <string>tc_upgrade_3_29_4</string>\r\n  " +
            "<string>tc_upgrade_3_30_1</string>\r\n  <string>tc_upgrade_3_30_2</string>\r\n  <str" +
            "ing>tc_upgrade_3_30_3</string>\r\n  <string>tc_upgrade_3_30_4</string>\r\n  <string>" +
            "tc_upgrade_3_30_5</string>\r\n  <string>tc_upgrade_3_30_6</string>\r\n  <string>tc_u" +
            "pgrade_3_31_1</string>\r\n  <string>tc_upgrade_3_31_2</string>\r\n  <string>tc_upgra" +
            "de_3_32_1</string>\r\n  <string>tc_upgrade_3_33_1</string>\r\n  <string>tc_upgrade_3" +
            "_34_1</string>\r\n  <string>tc_upgrade_3_34_2</string>\r\n  <string>tc_upgrade_3_34_" +
            "3</string>\r\n  <string>tc_upgrade_3_34_4</string>\r\n  <string>tc_upgrade_3_34_5</s" +
            "tring>\r\n  <string>tc_upgrade_3_34_6</string>\r\n  <string>tc_upgrade_3_34_7</strin" +
            "g>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SqlScripts {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SqlScripts"]));
            }
            set {
                this["SqlScripts"] = value;
            }
        }
    }
}
